services:
  api:
    container_name: fastapi-app
    ports:
      - "80:80"
    volumes:
      - .:/code
    build:
      dockerfile: ./Dockerfile
    restart: unless-stopped
    networks:
      - copilot

  db:
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: fastapi
      POSTGRES_USER: fastapi
      POSTGRES_PASSWORD: fastapi
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fastapi -d fastapi"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - copilot

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@domain.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5049:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - copilot

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped
    networks:
      - copilot

volumes:
  db_data:
   name: db_data
  qdrant_data:
    name: qdrant_data


networks:
  copilot:
    name: copilot